# NumPy

Numerical Python

In [7]:
!pip install numpy

In [8]:
import numpy as np

In [9]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [78]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [12]:
a.ndim

2

In [13]:
a.shape

(2, 4)

In [79]:
a = np.array([[[1,2,3,4],[5,6,7,8], [9,10,11,12]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [15]:
b = np.array(
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]]
    ]
)

In [80]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [81]:
b.ndim

3

In [18]:
b.shape

(3, 2, 2)

## Array
- np.array()
- np.zeros()
- np.ones()
- np.empty()
- np.arange()

In [19]:
np.array([1, 2, 3])

array([1, 2, 3])

In [20]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.empty((2, 2))

array([[1., 1.],
       [1., 1.]])

In [23]:
range(5)

range(0, 5)

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

## Add, Romove, Sort

- np.append()
- np.delete()
- np.sort()

In [25]:
arr = np.arange(8)
mylist = list(range(8))

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
mylist.append([1, 2])
mylist

[0, 1, 2, 3, 4, 5, 6, 7, [1, 2]]

In [28]:
np.append(arr, [[1, 2]])

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [29]:
arr = np.append(arr, [1, 2])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [30]:
np.delete(arr, 1)

array([0, 2, 3, 4, 5, 6, 7, 1, 2])

In [31]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [32]:
np.sort(arr)

array([0, 1, 1, 2, 2, 3, 4, 5, 6, 7])

In [33]:
print("dim", arr.ndim)
print("size", arr.size)
print("shape", arr.shape)

dim 1
size 10
shape (10,)


In [34]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [35]:
print("dim", a.ndim)
print("size", a.size)
print("shape", a.shape)

dim 3
size 12
shape (1, 3, 4)


In [36]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [37]:
print("dim", b.ndim)
print("size", b.size)
print("shape", b.shape)

dim 3
size 12
shape (3, 2, 2)


In [38]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [39]:
print("dim", array_example.ndim)
print("size", array_example.size)
print("shape", array_example.shape)

dim 3
size 24
shape (3, 2, 4)


## Reshape

In [40]:
arr = np.array([0,1,2,3,4,5,6,7,1,2])

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [42]:
arr.shape

(10,)

In [43]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 1, 2]])

In [44]:
arr.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

In [45]:
arr.reshape(5,2,1,1)

array([[[[0]],

        [[1]]],


       [[[2]],

        [[3]]],


       [[[4]],

        [[5]]],


       [[[6]],

        [[7]]],


       [[[1]],

        [[2]]]])

In [46]:
arr3 = arr.reshape(2,5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 1, 2]])

# Convert 1D to 2D
- np.newaxis
- np.expand_dims

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [48]:
arr.shape

(10,)

In [49]:
arr4 = arr[np.newaxis, :]
arr4

array([[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]])

In [50]:
arr4.ndim

2

In [51]:
arr4.shape

(1, 10)

In [52]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [53]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [54]:
a.shape

(1, 3, 4)

In [55]:
np.expand_dims(a, axis=0).shape

(1, 1, 3, 4)

In [56]:
a[np.newaxis, :].shape

(1, 1, 3, 4)

In [57]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
np.lookfor("compare")

Search results for 'compare'
----------------------------
numpy.compare_chararrays
    Performs element-wise comparison of two string arrays using the
numpy.lib._version.NumpyVersion
    Parse and compare numpy version strings.
numpy.ma.MaskedArray._comparison
    Compare self with other using operator.eq or operator.ne.
numpy.fmax
    Element-wise maximum of array elements.
numpy.fmin
    Element-wise minimum of array elements.
numpy.sort
    Return a sorted copy of an array.
numpy.equal
    Return (x1 == x2) element-wise.
numpy.testing.assert_array_almost_equal_nulp
    Compare two arrays relatively to their spacing.
numpy.nanmax
    Return the maximum of an array or maximum along an axis, ignoring any
numpy.nanmin
    Return minimum of an array or minimum along an axis, ignoring any NaNs.
numpy.argsort
    Returns the indices that would sort an array.
numpy.isclose
    Returns a boolean array where two arrays are element-wise equal within a
numpy.maximum
    Element-wise maximum of 

In [59]:
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 1, 2]])

np

In [82]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [61]:
help(np.expand_dims)

Help on _ArrayFunctionDispatcher in module numpy:

expand_dims(a, axis)
    Expand the shape of an array.
    
    Insert a new axis that will appear at the `axis` position in the expanded
    array shape.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int or tuple of ints
        Position in the expanded axes where the new axis (or axes) is placed.
    
        .. deprecated:: 1.13.0
            Passing an axis where ``axis > a.ndim`` will be treated as
            ``axis == a.ndim``, and passing ``axis < -a.ndim - 1`` will
            be treated as ``axis == 0``. This behavior is deprecated.
    
        .. versionchanged:: 1.18.0
            A tuple of axes is now supported.  Out of range axes as
            described above are now forbidden and raise an `AxisError`.
    
    Returns
    -------
    result : ndarray
        View of `a` with the number of dimensions increased.
    
    See Also
    --------
    squeeze : The inverse operation, r

In [62]:
arr.shape

(10,)

In [63]:
arr[np.newaxis]

array([[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]])

In [64]:
help(np.newaxis)

Help on NoneType object:

class NoneType(object)
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.



In [65]:
arr.shape

(10,)

In [66]:
arr4= arr[np.newaxis]

In [67]:
arr4

array([[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]])

In [68]:
arr4.ndim

2

In [69]:
arr4.shape

(1, 10)

In [70]:
np.expand_dims(arr4, 0)

array([[[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]]])

In [71]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [72]:
np.expand_dims(a,axis=2)

array([[[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]]])

In [73]:
a.shape

(1, 3, 4)

## Indexing and Slicing

arr

In [74]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [75]:
arr[4:]

array([4, 5, 6, 7, 1, 2])

In [76]:
arr[8]

1

In [77]:
arr[[False, True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10 but corresponding boolean dimension is 2

In [ ]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True, False,
       False])

In [ ]:
arr[arr > 2]

array([3, 4, 5, 6, 7])

In [ ]:
a[a<8].shape

(7,)

In [ ]:
a<8

array([[[ True,  True,  True,  True],
        [ True,  True,  True, False],
        [False, False, False, False]]])

In [ ]:
a % 2 == 0 #genap

array([[[False,  True, False,  True],
        [False,  True, False,  True],
        [False,  True, False,  True]]])

In [ ]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
a % 3 == 0 #gaanjil

array([[[False, False,  True, False],
        [False,  True, False, False],
        [ True, False, False,  True]]])

In [ ]:
(a % 2 == 0) & (a % 3 ==0)

array([[[False, False, False, False],
        [False,  True, False, False],
        [False, False, False,  True]]])

In [ ]:
a[(a % 2 == 0) & (a % 3 ==0)]

array([ 6, 12])

## Creating from Existing Data

- np.vstack()
- np.vstack()
- np.hstack()
- np.vsplit()
- np.hsplit()
- .view()
- .copy()


In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [ ]:
arr1 = arr[3:8]
arr1

array([3, 4, 5, 6, 7])

In [ ]:
help(np.vstack)

Help on _ArrayFunctionDispatcher in module numpy:

vstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    ``np.row_stack`` is an alias for `vstack`. They are the same function.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    dtype : str or dtype
        If provided, the destination array will have this dtype. Canno

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [ ]:
a_1 = np.array([[1,1],[2,2]])
print(a_1.shape)
a_1

(2, 2)


array([[1, 1],
       [2, 2]])

In [ ]:
a_1

array([[1, 1],
       [2, 2]])

In [ ]:
a_2 = np.array([[3,3], [4,4]])
print(a_2.shape)
a_2

(2, 2)


array([[3, 3],
       [4, 4]])

In [ ]:
a_2

array([[3, 3],
       [4, 4]])

In [ ]:
np.vstack([a_1, a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack([a_1, a_2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [83]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
    [13,14,15,16,17,18,19,20,21,22,23,24]])

In [ ]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [88]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [85]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [89]:
np.hsplit(a, 2)

ValueError: array split does not result in an equal division

In [90]:
np.vsplit(a, 3)

ValueError: array split does not result in an equal division

In [91]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [92]:
b = a

In [93]:
print(id(a))
print(id(b))
print(id(a) == id(b))

2946423577008
2946423577008
True


In [94]:
b = a.view()

In [95]:
print(id(a))
print(id(b))
print(id(a) == id(b))

2946423577008
2946424609872
False


In [96]:
c = a.copy()

In [97]:
print(id(a))
print(id(c))
print(id(a) == id(c))

2946423577008
2946424855152
False


## Basic Array Operations
- "+"
- '-'
- '/'
- '*'

In [98]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [ ]:
arr + 1

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3])

In [ ]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35,  5, 10])

In [ ]:
[1, 2,3] *5 #list

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
arr+np.array([5])

array([ 5,  6,  7,  8,  9, 10, 11, 12,  6,  7])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [ ]:
%%timeit
sum([1,2,3,4])

104 ns ± 1.06 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [ ]:
%%timeit
np.arange(1,5).sum()

2.13 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
data = np.array([1,2])
data

array([1, 2])

In [ ]:
ones = np.ones(2)
ones

array([1., 1.])

In [ ]:
data + ones

array([2., 3.])

In [ ]:
data * ones

array([1., 2.])

## Broadcasting

In [ ]:
data*2

array([2, 4])

In [ ]:
data+2

array([3, 4])

### Array Operations
- data.max()
- data.min()
- data.sum()
- data.mean()
- data.std()
- data.var()

In [99]:
%%timeit
sum([1, 2, 3, 4])

110 ns ± 3.75 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [100]:
%%timeit
np.arange(1, 5).sum()

2.68 µs ± 625 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [101]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [102]:
print(arr.sum())
print(arr.max())
print(arr.min())

31
7
0


In [103]:
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

31
7
0


In [ ]:
np.max(arr)

7

In [ ]:
print(arr.sum())
print(arr.max())
p

## Matrices

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [104]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [105]:
np.random.random((3, 2))

array([[0.75668031, 0.89882195],
       [0.58371302, 0.44091902],
       [0.18361227, 0.64168033]])

## Matrix Arithmetic

In [107]:
data = np.arange(1,5).reshape(2,2)
ones = np.ones((2,2))
ones_row= np.ones((1,2))

print(data)
print(ones)
print(ones_row)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]]


In [108]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [109]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [110]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [ ]:
# perkalian matrix
(2, 3) * (3, 2)  # a_1 * a_2

(3, 2) * (2, 3)  # a_2 * a_1

In [111]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [112]:
np.dot(a_2, a_1)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

## Matrix Indexing

In [114]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [118]:
a[0][0]

array([1, 2, 3, 4])

In [116]:
a[1][2]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [119]:
a[2][-1]

IndexError: index 2 is out of bounds for axis 0 with size 1

In [120]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [121]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [122]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [123]:
data.shape

(3, 2)

In [124]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [125]:
print(data.sum(axis=0))
print(data.sum(axis=1))

[ 9 12]
[ 3  7 11]


## Transposing

In [126]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [128]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [129]:
data.shape

(3, 2)

In [130]:
data.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [131]:
data.reshape((6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [132]:
data.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [133]:
np.arange(15).reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [134]:
np.linspace(0, 50, num=20).reshape((5, 4))

array([[ 0.        ,  2.63157895,  5.26315789,  7.89473684],
       [10.52631579, 13.15789474, 15.78947368, 18.42105263],
       [21.05263158, 23.68421053, 26.31578947, 28.94736842],
       [31.57894737, 34.21052632, 36.84210526, 39.47368421],
       [42.10526316, 44.73684211, 47.36842105, 50.        ]])

## N Dimensional Array

In [136]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [137]:
ndarr.shape

(2, 2, 2)

In [138]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [139]:
randomarr = np.random.random((4, 3, 2))
randomarr

array([[[0.16919067, 0.71965604],
        [0.7724076 , 0.72897276],
        [0.84075865, 0.20154103]],

       [[0.20699122, 0.32675855],
        [0.24741693, 0.1736883 ],
        [0.29569101, 0.32842787]],

       [[0.30898382, 0.05930125],
        [0.43316955, 0.05155622],
        [0.3651597 , 0.86027342]],

       [[0.97403677, 0.04182711],
        [0.43251414, 0.44844691],
        [0.82315139, 0.80085378]]])

In [140]:
randomarr.flatten()

array([0.16919067, 0.71965604, 0.7724076 , 0.72897276, 0.84075865,
       0.20154103, 0.20699122, 0.32675855, 0.24741693, 0.1736883 ,
       0.29569101, 0.32842787, 0.30898382, 0.05930125, 0.43316955,
       0.05155622, 0.3651597 , 0.86027342, 0.97403677, 0.04182711,
       0.43251414, 0.44844691, 0.82315139, 0.80085378])

In [141]:
randomarr.reshape(-1)

array([0.16919067, 0.71965604, 0.7724076 , 0.72897276, 0.84075865,
       0.20154103, 0.20699122, 0.32675855, 0.24741693, 0.1736883 ,
       0.29569101, 0.32842787, 0.30898382, 0.05930125, 0.43316955,
       0.05155622, 0.3651597 , 0.86027342, 0.97403677, 0.04182711,
       0.43251414, 0.44844691, 0.82315139, 0.80085378])

In [142]:
randomarr.reshape(24,)

array([0.16919067, 0.71965604, 0.7724076 , 0.72897276, 0.84075865,
       0.20154103, 0.20699122, 0.32675855, 0.24741693, 0.1736883 ,
       0.29569101, 0.32842787, 0.30898382, 0.05930125, 0.43316955,
       0.05155622, 0.3651597 , 0.86027342, 0.97403677, 0.04182711,
       0.43251414, 0.44844691, 0.82315139, 0.80085378])

## Math Formulas

In [145]:
np.sqrt(25)

5.0